export const OFFICE_PAGES = Object.freeze({"/office":"home","/office/work":"work","/office/results":"results","/office/sales":"sales","/office/files":"files","/office/tools":"tools","/office/history":"history","/office/system":"system","/office/settings":"settings"});
const labels={home:"หน้าแรก",work:"งานของบิ๊ก",results:"ผลงาน",sales:"หน้าร้าน",files:"ไฟล์",tools:"เครื่องมือ",history:"ประวัติงาน",system:"สถานะการเชื่อมต่อ",settings:"ตั้งค่า"};
const tracker = "<section class=\"office-panel office-workspace\" data-work-tracker><div class=\"office-workspace-head\"><div><p class=\"office-kicker\">WORK TRUTH</p><h3>ติดตามงานจริงจาก Centre</h3><p class=\"office-muted\">ปัก Work ID + Checkpoint ID แล้ว Office จะอ่านสถานะจริงจาก owner truth โดยไม่สร้าง authority ใหม่</p></div><button type=\"button\" data-work-refresh>Refresh</button></div><form class=\"office-work-form\" data-work-form><input name=\"workId\" autocomplete=\"off\" placeholder=\"WORK-...\" required><input name=\"checkpointId\" autocomplete=\"off\" placeholder=\"CP-...\" required><button type=\"submit\">Track work</button></form><p class=\"office-muted\" data-work-message>ยังไม่ได้ปักงาน</p><div class=\"office-work-list\" data-work-list></div></section>";
const spectrum = "<section class=\"office-panel office-spectrum\" data-spectrum-work><div><p class=\"office-kicker\">SPECTRUM · WORK</p><h3>สั่งงานให้โก</h3><p class=\"office-muted\">บอกงานและสิ่งที่อยากได้ แล้วส่งเข้าระบบงานเดิม</p><form class=\"office-spectrum-create\" data-spectrum-create><input name=\"mission\" placeholder=\"งานที่ต้องทำ\" required><input name=\"requestedResult\" placeholder=\"ผลลัพธ์ที่ต้องการ\" required><input name=\"workKey\" placeholder=\"Work key (ถ้ามี)\"><button type=\"submit\">เริ่มงาน</button></form><form class=\"office-spectrum-pickup\" data-spectrum-pickup><input name=\"tabletId\" placeholder=\"TABLET:...\" required><button type=\"submit\">เปิดใบงาน</button></form><p class=\"office-muted\" data-spectrum-status>พร้อมรับงาน</p></div></section>";
const assets = "<section class=\"office-panel office-assets\" data-office-assets><div><p class=\"office-kicker\">ASSETS</p><h3>ไฟล์ของบิ๊ก</h3><p class=\"office-muted\">ภาพและไฟล์ของบิ๊ก · เปิดดูและดาวน์โหลดได้จากที่นี่</p><form data-asset-upload><input type=\"file\" name=\"file\" accept=\"image/png,image/jpeg,image/webp\" required><select name=\"category\"><option value=\"uploads\">ไฟล์ทั่วไป</option><option value=\"visuals\">ภาพ</option><option value=\"projects\">โครงการ</option><option value=\"references\">ภาพอ้างอิง</option></select><button type=\"submit\">อัปโหลด</button></form><p class=\"office-muted\" data-asset-status>พร้อมรับไฟล์</p><ul class=\"office-asset-list\" data-asset-list></ul></div></section>";
const security = "<section class=\"office-panel\"><div><p class=\"office-kicker\">SECURITY</p><h3>Passkey</h3><p class=\"office-muted\" data-passkey-status>ตรวจสถานะ Passkey…</p></div><button type=\"button\" data-passkey-register>Create Passkey</button></section>";
const observer = "<section class=\"office-panel\"><div><p class=\"office-kicker\">OBSERVER</p><h3>GO can see the current screen</h3><p class=\"office-muted\" data-eye-message>กำลังอ่านสถานะ Factory Eye…</p></div><div><button type=\"button\" data-eye-observe>Observe now</button><button type=\"button\" data-eye-refresh>Refresh status</button></div></section>";
const refresh='<button type="button" data-overview-refresh>อัปเดต</button>';
const workList=(title,view='current')=>`<section class="office-panel" data-work-view="${view}"><div class="office-section-heading"><h2>${title}</h2>${refresh}</div><p class="office-muted" data-overview-coverage>กำลังอ่านงาน…</p><div class="office-work-list" data-overview-works></div><button type="button" data-overview-more hidden>ดูงานเพิ่ม</button></section>`;
const destinations=`<div class="office-launch-grid"><a href="https://go-hub.pureekangraw.workers.dev/pixie-visual-workbench" target="_blank" rel="noopener noreferrer"><strong>โต๊ะทำภาพ ↗</strong><span>วางภาพอ้างอิง เตรียมโจทย์ และดูภาพบนโต๊ะ</span></a><a href="/office/files"><strong>ไฟล์ของบิ๊ก</strong><span>เปิดไฟล์ ดาวน์โหลด หรืออัปโหลดภาพ</span></a><a href="/office/results"><strong>ผลงานที่เสร็จแล้ว</strong><span>ดูผลลัพธ์และเปิดหลักฐานของงาน</span></a><a href="/office/sales"><strong>ข้อมูลจากหน้าร้าน</strong><span>ดูบรีฟลูกค้าและสิ่งที่มีคนสนใจ</span></a></div>`;
const dailySummary=`<section class="office-daily-summary" data-daily-summary aria-labelledby="daily-summary-title"><div class="office-section-heading"><div><p class="office-kicker">DAILY SUMMARY</p><h2 id="daily-summary-title">ภาพรวมปัจจุบัน</h2></div>${refresh}</div><p class="office-muted" data-summary-status role="status" aria-live="polite">กำลังอ่าน owner-source…</p><div class="office-summary-grid"><article data-summary-lens="SALES"><span>SALES</span><strong>—</strong><p>บรีฟและใบเสนอราคา</p></article><article data-summary-lens="MONEY"><span>MONEY</span><strong>—</strong><p>provider evidence · GO review</p></article><article data-summary-lens="WORK"><span>WORK</span><strong>—</strong><p>งานปัจจุบัน</p></article><article data-summary-lens="SYSTEM"><span>SYSTEM</span><strong>—</strong><p>จุดเชื่อมต่อ</p></article><article data-summary-lens="ATTENTION"><span>ATTENTION</span><strong>—</strong><p>สิ่งที่ควรตรวจ</p></article></div></section>`;
export function officeShell(page='home') {
  let content='';
  if(page==='home')content=`<section class="office-welcome"><h2>วันนี้มีอะไรให้บิ๊กดูบ้าง</h2><p>สรุปยอดจาก owner-source ก่อน ตามด้วยสิ่งที่กำลังขยับ</p></section>${dailySummary}${destinations}<section class="office-panel"><div class="office-section-heading"><div><p class="office-kicker">LIVE MOVEMENT</p><h2>ตอนนี้ระบบกำลังขยับอะไร</h2></div>${refresh}</div><p class="office-muted" data-overview-activity-status>กำลังอ่านการเคลื่อนไหว…</p><div class="office-activity-list" data-overview-activity></div></section>${workList('งานวันนี้')}<p class="office-page-links"><a href="/office/work">ดูงานปัจจุบันทั้งหมด →</a><a href="/office/history">ประวัติงาน</a></p>`;
  if(page==='work')content=`${workList('งานของบิ๊ก')}<p class="office-page-links"><a href="/office/history">ดูงานเก่าและงานยกเลิก →</a></p><details class="office-tools"><summary>ติดตามด้วยรหัสงาน</summary>${tracker}</details>`;
  if(page==='history')content=`<p class="office-muted">งานที่เสร็จแล้ว ยกเลิกแล้ว และรายการทดสอบ แยกเก็บไว้ที่นี่</p>${workList('ประวัติงาน','history')}`;
  if(page==='results')content=`<section class="office-panel" data-work-view="results"><div class="office-section-heading"><h2>ผลงานที่เสร็จแล้ว</h2>${refresh}</div><p class="office-muted" data-overview-coverage>กำลังอ่านผลงาน…</p><div class="office-work-list" data-overview-results></div><button type="button" data-overview-more hidden>ดูผลงานเพิ่ม</button></section>`;
  if(page==='sales')content=`<section class="office-panel"><div class="office-section-heading"><h2>ข้อมูลจากหน้าร้าน</h2>${refresh}</div><p class="office-muted" data-overview-sales-status>กำลังอ่านข้อมูล…</p><div class="office-work-list" data-overview-sales></div><button type="button" data-sales-more hidden>ดูข้อมูลเพิ่ม</button></section><section class="office-panel"><div class="office-section-heading"><h2>ใบเสนอราคา</h2>${refresh}</div><p class="office-muted">ยอดและสกุลเงินจาก Office เป็น owner truth ก่อนสร้าง checkout</p><form class="office-quote-form" data-quote-form><input name="quoteId" placeholder="QUOTE-..." required><input name="customerId" placeholder="Customer ID" required><input name="workId" placeholder="WORK-..." required><input name="amount" type="number" min="0.01" step="0.01" placeholder="ยอดเงิน" required><input name="currency" maxlength="3" value="THB" required><select name="status"><option value="QUOTE_DRAFT">บันทึกร่าง</option><option value="QUOTE_SENT">ส่งใบเสนอราคาแล้ว</option></select><button type="submit">บันทึก Quote</button></form><p class="office-muted" data-quote-status>ยังไม่ได้บันทึก</p><div class="office-work-list" data-overview-quotes></div></section><section class="office-panel"><div class="office-section-heading"><h2>การชำระเงิน</h2>${refresh}</div><p class="office-muted">อ่านสถานะจาก payment provider โดยไม่แสดงข้อมูลบัตรหรือ secret</p><div class="office-work-list" data-overview-payments></div></section>`;
  if(page==='files')content=assets;
  if(page==='tools')content=`<h2>เปิดพื้นที่ทำงาน</h2>${destinations}<p class="office-muted">โต๊ะภาพใช้เตรียมโจทย์และตรวจภาพ ส่วนการสร้างภาพยังทำผ่านโก</p><details class="office-tools"><summary>ส่งงานใหม่ให้โก</summary>${spectrum}</details><p class="office-muted">ผู้ช่วย Copilot: ยังไม่พบทางเข้าหน้าเว็บที่ยืนยันได้</p>`;
  if(page==='system')content=`<section class="office-panel"><div class="office-section-heading"><div><p class="office-kicker">SYSTEM HEALTH</p><h2>สุขภาพระบบ</h2></div>${refresh}</div><div class="office-health-summary" data-overview-health></div><div class="office-mismatch-list" data-overview-mismatches></div></section><section class="office-panel"><div class="office-section-heading"><h2>สถานะการเชื่อมต่อ</h2>${refresh}</div><p class="office-muted">หน้านี้ใช้ตรวจระบบ ไม่ใช่ทางเข้าเครื่องมือ</p><div class="office-component-grid" data-overview-system></div></section><details class="office-tools"><summary>ภาพหน้าจอสำหรับตรวจระบบ</summary><div class="office-eye" data-office-eye><strong data-eye-state>กำลังตรวจ</strong><small data-eye-detail></small></div>${observer}</details>`;
  if(page==='settings')content=security;
  const nav=Object.entries(labels).filter(([key])=>['home','work','results','sales','files','tools'].includes(key)).map(([key,label])=>`<a href="${key==='home'?'/office':'/office/'+key}" ${page===key?'aria-current="page"':''}>${label}</a>`).join('');
  return `<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b1118"><title>${labels[page]} · Office</title><link rel="stylesheet" href="/go-hub-office-surface.css"></head><body class="office-body" data-office-page="${page}"><!-- OFFICE_EDIT_ROUTE:GITHUB_DIRECT --><main class="office-shell"><header class="office-top"><div><p class="office-kicker">YGG METRO</p><h1>Office</h1><p class="office-muted">พื้นที่ทำงานของบิ๊ก</p></div><form method="post" action="/office/logout"><button class="office-quiet" type="submit">ออกจากระบบ</button></form></header><nav class="office-tabs" aria-label="เมนู Office">${nav}</nav><div class="office-page-content">${content}</div><footer class="office-footer"><a href="/office/settings">ตั้งค่า</a><a href="/office/system">ตรวจการเชื่อมต่อ</a><a href="/office/history">ประวัติงาน</a></footer></main><script type="module" src="/go-hub-office-surface.js"></script></body></html>`;
}
